[package]
authors = ["Theodore Bjernhed <uik1475@edu.kunskapsskolan.se>"]
categories = ["game-development", "graphics", "multimedia::images", "rendering"]
description = "A simple library for rendering SVGs in Bevy using the amazing Resvg library."
edition = "2024"
exclude = ["cliff.toml", "release.toml", "sumi.toml"]
keywords = ["bevy", "gamedev", "graphics", "render", "svg"]
license = "MIT OR Apache-2.0"
name = "bevy_resvg"
readme = "README.md"
repository = "https://github.com/theodorebje/bevy_resvg"
rust-version = "1.89"
version = "2.2.0"

[dependencies]
bevy = { version = "0.18", default-features = false, features = [
    "bevy_log",
    "bevy_sprite_render",
    "bevy_ui",
    "std",
] }
resvg = ">=0.42, ^0.47"
serde = { version = "1.0", features = ["derive"] }
thiserror = ">=1.0, <3.0"

[patch.crates-io]
usvg = { git = 'https://github.com/theodorebje/usvg-serde.git' }

[dev-dependencies]
bevy = { version = "0.18", default-features = true, features = ["debug"] }
bevy_pancam = "0.20"

[lints.clippy]
needless_pass_by_value = { priority = 1, level = "allow" } # Bevy freaks out over references
nursery = "deny"
pedantic = "deny"
type_complexity = { priority = 1, level = "allow" }        # Bevy queries are inherently complex
